import assert from "node:assert/strict";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { load } from "cheerio";

import { loadSiteContract } from "./site-contract.mjs";

export const siteOrigin = "https://hyle-labs.net";
export const localeRoutes = Object.freeze({
    fr: "/",
    en: "/en/",
    es: "/es/",
    zh: "/zh/"
});
export const generatedLocaleFiles = Object.freeze({
    en: "en/index.html",
    es: "es/index.html",
    zh: "zh/index.html"
});

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const generatedMarker = (language) =>
    `<!-- Generated by scripts/build-locales.mjs for ${language}. Do not edit directly. -->`;

const directTextNode = ($, element) =>
    $(element).contents().toArray().find((node) =>
        node.type === "text" && (node.data || "").trim()
    );

const writeBinding = ($, element, type, value) => {
    if (type === "html") {
        element.html(value);
        return;
    }
    if (type === "label") {
        const textNode = directTextNode($, element);
        assert(textNode, `Cannot locate the direct label text for ${element.prop("tagName")}`);
        const leading = textNode.data.match(/^\s*/)?.[0] || "";
        const trailing = textNode.data.match(/\s*$/)?.[0] || "";
        textNode.data = `${leading}${value}${trailing}`;
        return;
    }
    if (type.startsWith("attr:")) {
        element.attr(type.slice(5), value);
        return;
    }
    element.text(value);
};

const setLocalizedMetadata = ($, language, contract) => {
    const { htmlLang, ogLocale } = contract.supportedLanguages[language];
    const meta = contract.pageMeta[language];
    const canonicalUrl = `${siteOrigin}${localeRoutes[language]}`;

    $("html").attr("lang", htmlLang).attr("data-site-locale", language);
    $("title").text(meta.title);
    $('meta[name="description"]').attr("content", meta.description);
    $('meta[property="og:title"]').attr("content", meta.ogTitle);
    $('meta[property="og:description"]').attr("content", meta.ogDescription);
    $('meta[property="og:image:alt"]').attr("content", meta.ogImageAlt);
    $('meta[property="og:image"]').attr("content", `${siteOrigin}/${meta.ogImage}`);
    $('meta[name="twitter:image"]').attr("content", `${siteOrigin}/${meta.ogImage}`);
    $('meta[name="twitter:title"]').attr("content", meta.ogTitle);
    $('meta[name="twitter:description"]').attr("content", meta.ogDescription);
    $('meta[name="twitter:image:alt"]').attr("content", meta.ogImageAlt);
    $('meta[property="og:locale"]').attr("content", ogLocale);
    $('meta[property="og:url"]').attr("content", canonicalUrl);
    const ogLocaleElement = $('meta[property="og:locale"]').first();
    $('meta[property="og:locale:alternate"]').remove();
    let previousLocaleElement = ogLocaleElement;
    for (const alternateLanguage of Object.keys(localeRoutes)) {
        if (alternateLanguage === language) continue;
        const alternateElement = $(
            `<meta property="og:locale:alternate" content="${contract.supportedLanguages[alternateLanguage].ogLocale}">`
        );
        previousLocaleElement.after(alternateElement);
        previousLocaleElement = alternateElement;
    }
    $('link[rel="canonical"]').attr("href", canonicalUrl);

    for (const [alternateLanguage, route] of Object.entries(localeRoutes)) {
        const hreflang = contract.supportedLanguages[alternateLanguage].htmlLang;
        $(`link[rel="alternate"][hreflang="${hreflang}"]`).attr(
            "href",
            `${siteOrigin}${route}`
        );
    }
    $('link[rel="alternate"][hreflang="x-default"]').attr("href", `${siteOrigin}/`);

    const schemaElement = $('script[type="application/ld+json"]').first();
    const schema = JSON.parse(schemaElement.text());
    const graph = schema["@graph"];
    const software = graph.find((item) => item["@type"] === "SoftwareApplication");
    const faq = graph.find((item) => item["@type"] === "FAQPage");
    assert(software && faq, "SoftwareApplication and FAQPage JSON-LD nodes are required");
    software["@id"] = `${canonicalUrl}#taveni`;
    software.url = canonicalUrl;
    software.description = meta.schemaDescription;
    software.inLanguage = htmlLang;
    faq["@id"] = `${canonicalUrl}#faq`;
    faq.inLanguage = htmlLang;
    faq.mainEntity = [1, 2, 3, 4, 5].map((number) => ({
        "@type": "Question",
        name: contract.translations[language][`faq.${number}.q`],
        acceptedAnswer: {
            "@type": "Answer",
            text: contract.translations[language][`faq.${number}.a`]
        }
    }));
    schemaElement.text(JSON.stringify(schema, null, 2));
};

const makeRootRelativeAssets = ($) => {
    for (const attribute of ["src", "href"]) {
        $(`[${attribute}]`).each((_index, node) => {
            const element = $(node);
            const reference = element.attr(attribute);
            if (!reference || reference.startsWith("/") || reference.startsWith("#")) return;
            if (/^(?:https?:|mailto:|tel:|data:)/.test(reference)) return;
            element.attr(attribute, `/${reference}`);
        });
    }

    $("style").each((_index, node) => {
        const element = $(node);
        element.text(
            element.text().replace(/url\((["']?)assets\//g, "url($1/assets/")
        );
    });
};

export const renderLocalizedPage = (language, sourceHtml, contract) => {
    assert(Object.hasOwn(generatedLocaleFiles, language), `Unsupported generated locale: ${language}`);
    const $ = load(sourceHtml, { decodeEntities: false });

    for (const [key, selector, type] of contract.bindings) {
        const element = $(selector).first();
        assert(element.length, `Missing binding target ${selector}`);
        const value = contract.translations[language]?.[key];
        assert.equal(typeof value, "string", `Missing ${language} translation for ${key}`);
        writeBinding($, element, type, value);
    }

    setLocalizedMetadata($, language, contract);
    makeRootRelativeAssets($);
    $(".language-button").removeAttr("aria-current");
    $(`.language-button[data-lang="${language}"]`).attr("aria-current", "page");

    const serialized = $.html();
    const output = serialized.replace(
        /^<!DOCTYPE html>/i,
        `<!DOCTYPE html>\n${generatedMarker(language)}\n`
    );
    return output.endsWith("\n") ? output : `${output}\n`;
};

export const renderSitemap = (contract) => {
    const entries = Object.entries(localeRoutes).map(([language, route]) => {
        const alternates = Object.entries(localeRoutes).map(([alternateLanguage, alternateRoute]) =>
            `    <xhtml:link rel="alternate" hreflang="${contract.supportedLanguages[alternateLanguage].htmlLang}" href="${siteOrigin}${alternateRoute}"/>`
        );
        alternates.push(
            `    <xhtml:link rel="alternate" hreflang="x-default" href="${siteOrigin}/"/>`
        );
        return [
            "  <url>",
            `    <loc>${siteOrigin}${route}</loc>`,
            ...alternates,
            "  </url>"
        ].join("\n");
    });
    return [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
        '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
        ...entries,
        "</urlset>",
        ""
    ].join("\n");
};

export const generateLocalizedArtifacts = (root = repoRoot) => {
    const sourceHtml = readFileSync(resolve(root, "index.html"), "utf8");
    const contract = loadSiteContract(root);
    const artifacts = new Map();
    for (const [language, relativePath] of Object.entries(generatedLocaleFiles)) {
        artifacts.set(relativePath, renderLocalizedPage(language, sourceHtml, contract));
    }
    artifacts.set("sitemap.xml", renderSitemap(contract));
    return artifacts;
};

const run = () => {
    const checkOnly = process.argv.includes("--check");
    const artifacts = generateLocalizedArtifacts();
    const stale = [];

    for (const [relativePath, expected] of artifacts) {
        const outputPath = resolve(repoRoot, relativePath);
        if (checkOnly) {
            let actual = null;
            try {
                actual = readFileSync(outputPath, "utf8");
            } catch {
                // A missing generated artifact is stale by definition.
            }
            if (actual !== expected) stale.push(relativePath);
            continue;
        }
        mkdirSync(dirname(outputPath), { recursive: true });
        writeFileSync(outputPath, expected, "utf8");
    }

    if (stale.length) {
        throw new Error(
            `Generated locale artifacts are stale or missing: ${stale.join(", ")}. Run npm run build.`
        );
    }
    console.log(
        checkOnly
            ? `Generated locale check passed: ${artifacts.size} artifacts are current.`
            : `Generated ${artifacts.size} locale artifacts.`
    );
};

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
    run();
}
